[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'rm -rf node_modules/.cache || true',
  'npm config set cache /tmp/.npm-cache',
  'npm ci --no-audit --prefer-offline --no-optional'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'
